---
abstract: 'AMQP binding for AnyMQ'
author:
  - 'Chia-liang Kao <clkao@clkao.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyMQ-AMQP
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  AnyEvent::RabbitMQ: 1.03
  AnyMQ: 0
  File::ShareDir: 0
  JSON: 0
  Try::Tiny: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/clkao/AnyMQ-AMQP.git
version: 0.30
